# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a9ac638d649ab71cc209d0d4892de72ca231a92eb5bb64599a18ca06ef5d43d853a7292953b659d24f9336f37e592628369eed507eb2275e7b2668e4fa7026d

test:
  secret_key_base: 0430c3d829befd2f12ed1a829557b32f32a62dafbf2f7dcd69ae941c6c41a2b9c0969e2db83c53768e209a492555d18955680b8eb4581f6da3d3ae1dbda857b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
